### ISSUE TITLE
Size display and example data sets in "Browse Dataset"

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-data-portal#1]
- [x] ~Homepage clean-up, add link to instruction repo and DESC homepage~ (moved to #32)
- [x] ~In the “Browse Dataset” view, the title format is off~ (moved to #23)
- [x] In the “Browse Dataset” view, list the size in MB or GB
- [x] In the “Browse Dataset” view, is there a way to add a “Select an example subset” button, which when clicked on, will check say 4 tracts that we use in the notebooks (we’ll need to update the notebooks to match the selection, of course)? Users may not know what “tracts” means when they reach this page, and even if they do, they may not know which tracts they should download if they want to just try out the notebooks.
- [x] In the “Browse Dataset” view, is it possible to display the total size of the files a user has chosen?

**Comment by yymao** [comment]
Homepage cleaning up was taken care by other PRs. 

I'm moving "In the “Browse Dataset” view, the title format is off" to another issue so that this issue is only about size display and example data sets.
