### ISSUE TITLE
reorganize docs

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/desc-data-portal#38]
Currently the list of documentation is:
<hr>

- How to download data files
- Globus Personal Connect
- Installing GCRCatalogs
- Accessing data files with GCRCatalogs
- Using cosmoDC2
- References (introduced in #37)
- Need Help?
<hr>

I am thinking that we may want to reorganize/regroup them into general instructions and documentation for specific data sets:

<hr>

#### General Instructions
- Download data files
- Set up Globus Personal Connect
- Install GCRCatalogs

#### Documentation for specific data sets
- DC2 Simulated Sky Survey
- CosmoDC2

#### Need Help?
- Post a questions here!

<hr>

The items under "General Instructions" would correspond to the first three items. The "DC2 Simulated Sky Survey" page would look more like the "CosmoDC2" page, but replace cosmoDC2 specifics with DC2 specifics.

The current "Accessing data files with GCRCatalogs" can disappear because the generic part about GCRCatalogs can go to "Install GCRCatalogs", and the DC2 specific part can go to "DC2 Simulated Sky Survey". 

"References" will also be directly written in the pages within "Documentation for specific data sets". Similar of the "Using cosmoDC2" that we currently have. 

This reorganization would also address some recent feedback we got from Stephane Plaszczynski. 
 
What do people think? (cc @heather999 @JoanneBogart @katrinheitmann)

**Comment by katrinheitmann** [comment]
I like that. The request for the reference to the papers when using the data might be buried too much? As we discussed, people familiar with globus might go directly to the download. They also might have read the DC2 paper already. So it could happen that they do not click on the "references" link? We could add it to the title of the link (References and how to ackn...) but that gets long.

**Comment by yymao** [comment]
Maybe we can add a new bullet point "How to acknowledge if you use these data sets" (or similar) under "General Instructions".

**Comment by katrinheitmann** [comment]
yes, that would work.

**Comment by JoanneBogart** [comment]
This all sounds very good.
