### ISSUE TITLE
Minor style issues

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/desc-data-portal#57]
- [x] decrease that gap at the bottom under footer 
- [x] add top margin for h4-6
- [x] make logo on home page smaller; align it with text

**Comment by JoanneBogart** [comment]
- [ ] Display of links is not consistent

A few display as underlined all the time.  For most you have to hover to see the underline.  Personally, I like to know what's a link without having to hover, but in any case we should be consistent.
