### ISSUE TITLE
Minor text edits

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/desc-data-portal#59]
Comments from @sethdigel https://lsstc.slack.com/archives/C01E1FG9Y4B/p1610590119007700

- In order to get some experience with the data we have provided Jupyter notebooks for each dataset. GCRCatalogs is required in order to run them. -> [From this page it is not immediately obvious where they are.  Maybe change the heading ‘Instructions Specific to Data Set’ to ‘Instructions and Notebooks Specific to Data Sets’]

- DESC acknowledges ongoing support from the US Department of Energy, IN2P3 (France), the STFC (United Kingdom), and the NSF and LSST Corporation (United States). -> [I notice that only Department of Energy is spelled out.  I can’t think of a good reason not to spell out the others]

**Comment by JoanneBogart** [comment]
In this sentence on the download page

"If you want to download files to a local machine (e.g., your laptop), you will need to set up Globus Personal Connect on your local machine first."

some part of it, say "set up Globus Personal Connect", should link to globus_personal

**Comment by yymao** [comment]
@JoanneBogart: note that the Globus Personal Connect link has been fixed by @heather999 in #61

**Comment by JoanneBogart** [comment]
And I see it's merged, so I will rebase.  Thanks!

**Comment by yymao** [comment]
Fixed by #64
