### ISSUE TITLE
Release calexps for tracts 3828 and 3829

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-data-portal#84]
As [discussed on Slack](https://lsstc.slack.com/archives/C01E1FG9Y4B/p1630696339002500)

### To Do List

- [x] Copy calexp, src catalog, and raw data into the appropriate area for the data portal - Heather
- [x] Update Portal documentation, and mention calexp - Joanne (?)
- [x] Update DC2 Data Release Note - Yao (?)
- [x] Copy data to ANL shared endpoint - Katrin
- [x] Update portal yaml to include calexp data - Heather
- [x] Deploy new portal to dev server - Heather
- [x] Release new version to the production server - Heather
- [x] Announce on #desc-announce and Community - Joanne (?)

**Comment by jbkalmbach** [comment]
Hi, I just wanted to check in on this issue and see if it's still possible to release this data? Thanks!

**Comment by jbkalmbach** [comment]
Sounds good. Thank you!

**Comment by heather999** [comment]
I'm copying over the raw (1.3 GB), calexp (28 TB), and src (1.6 TB) data for tracts 3828 and 3829 into
`/global/cfs/cdirs/lsst/gsharing/lsstdesc-public/dc2/run2.2i-dr6-v2/raw-t3828-t3829` and `/global/cfs/cdirs/lsst/gsharing/lsstdesc-public/dc2/run2.2i-dr6-v2/calexp-t3828-t3829`
I'll make a "small" subset for patch 2,2 of each tract just as we did for the coadd data.

**Comment by heather999** [comment]
@jbkalmbach Just wanted to let you know that this is finally released and available on the DC2 portal: data.lsstdesc.org

**Comment by jbkalmbach** [comment]
Thank you!!

**Comment by yymao** [comment]
:tada:
